name: Run tests

on: [push, pull_request]

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - php: 8.3
                      laravel: ^11.0
                    - php: 8.2
                      laravel: ^11.0
                    - php: 8.2
                      laravel: ^10.0
                    - php: 8.1
                      laravel: ^10.0
                    - php: 8.1
                      laravel: ^9.0

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Update composer
              run: composer self-update --2

            - name: Install dependencies
              run: composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-progress --no-suggest

            - name: Execute tests
              run: composer test
